[arch]
packages = [
  # cli & core
  "base-devel",
  "git",
  "stow",
  "fastfetch",
  "btop",
  "bat",
  "shellcheck",
  "starship",
  "rbw",
  "libyaml",
  "zellij",
  "lazygit",
  "lazydocker",
  "tree-sitter-cli",
  "neovim",
  "micro",
  "lua",
  "luarocks",
  "fzf",
  "ripgrep",
  "fd",
  "mise",
  "nano",
  "nano-syntax-highlighting",
  "paru",

  # wayland core
  { name = "sddm", hooks = { after_install = [
    "sudo",
    "systemctl",
    "enable",
    "sddm"
  ] } },
  "niri-git",
  "adw-gtk-theme",
  "gnome-keyring",
  "noto-fonts",
  "noto-fonts-emoji",
  "wl-clipboard",
  "wlsunset",
  "xdg-desktop-portal-gnome",
  "xdg-desktop-portal-gtk",
  "xwayland-satellite",
  "brightnessctl",
  "wlr-randr",
  "ddcutil",
  "cliphist",
  "wtype",
  { name = "swayidle", hooks = { after_install = [
    "systemctl",
    "--user",
    "add-wants",
    "niri.service",
    "swayidle.service"
  ] } },
  "xdg-terminal-exec",

  # graphics & multimedia
  "imagemagick",
  "ffmpeg",
  "qt6-multimedia-ffmpeg",
  "python",
  "cava",
  "matugen",
  "kimageformats",

  # gui apps
  "foot",
  "ghostty",
  "zed",
  "nautilus",
  "nautilus-python",
  "sushi",
  "cups-pk-helper",

  # shell / dms-shell deps
  "noctalia-qs",

  # network
  "iwd",
  "networkmanager",
  "networkmanager-openvpn",
  "wireguard-tools",
  "wireless-regdb",
  "nss-mdns",
  "dnsutils",
  "dnsmasq",
  "ethtool",
  { name = "iwd", hooks = { after_install = [
    "sudo",
    "systemctl",
    "enable",
    "--now",
    "iwd"
  ] } },
  { name = "networkmanager", hooks = { after_install = [
    "bash",
    "-c",
    "systemctl is-enabled wpa_supplicant &>/dev/null && sudo systemctl disable --now wpa_supplicant; grep -q 'wifi.backend=iwd' /etc/NetworkManager/NetworkManager.conf 2>/dev/null || printf '[device]\nwifi.backend=iwd\n' | sudo tee /etc/NetworkManager/NetworkManager.conf; sudo systemctl enable --now NetworkManager"
  ] } },

  # AUR
  "peazip-qt-bin",
  "helium-browser-bin",
  "jetbrains-toolbox",
  "visual-studio-code-bin",
  { name = "dms-shell-bin", hooks = { after_install = [
    "systemctl",
    "--user",
    "add-wants",
    "niri.service",
    "dms"
  ] } },
  { name = "dsearch-bin", hooks = { after_install = [
    "systemctl",
    "--user",
    "enable",
    "--now",
    "dsearch.service"
  ] } },
  "qt6ct-kde",
  "maplemono-nf-unhinted",
  "uv"
]

[uv]
packages = [
  "terminaltexteffects",
]
