[arch]
packages = [
  # cli & core
  "base-devel",
  "git",
  "stow",
  "btop",
  "bat",
  "shellcheck",
  "starship",
  "rbw",
  "libyaml",
  "zellij",
  "lazygit",
  "lazydocker",
  "tree-sitter-cli",
  "neovim",
  "micro",
  "lua",
  "luarocks",
  "fzf",
  "ripgrep",
  "fd",
  "mise",
  "nano",
  "nano-syntax-highlighting",
  "paru",

  # wayland core
  { name = "sddm", hooks = { after_install = ["sudo", "systemctl", "enable", "sddm"] } },
  "niri-git",
  "adw-gtk-theme",
  "gnome-keyring",
  "noto-fonts",
  "noto-fonts-emoji",
  "wl-clipboard",
  "wlsunset",
  "xdg-desktop-portal-gnome",
  "xdg-desktop-portal-gtk",
  "xwayland-satellite",
  "brightnessctl",
  "wlr-randr",
  "ddcutil",
  "cliphist",
  "wtype",
  "swayidle",
  "xdg-terminal-exec",

  # graphics & multimedia
  "imagemagick",
  "ffmpeg",
  "qt6-multimedia-ffmpeg",
  "python",
  "cava",
  "matugen",
  "kimageformats",

  # gui apps
  "foot",
  "ghostty",
  "zed",
  "nautilus",
  "nautilus-python",
  "sushi",
  "cups-pk-helper",

  # shell / dms-shell deps
  "noctalia-qs",

  # AUR
  "helium-browser-bin",
  "jetbrains-toolbox",
  "visual-studio-code-bin",
  { name = "dms-shell-bin", hooks = { after_install = ["systemctl", "--user", "add-wants", "niri.service", "dms"] } },
  { name = "dsearch-bin", hooks = { after_install = ["systemctl", "--user", "enable", "--now", "dsearch.service"] } },
  "qt6ct-kde",
  "maplemono-nf-unhinted",
  "uv"
]

[uv]
packages = [
  "terminaltexteffects",
]
