[arch]
packages = [
  { name = "flatpak", hooks = { after_install = [
    "sudo",
    "flatpak",
    "mask",
    "org.freedesktop.Platform.openh264"
  ] } },
]

[flatpak]
repos = [
  { name = "system:flathub", options = { url = "https://dl.flathub.org/repo/flathub.flatpakrepo" } },
]
packages = [
  { name = "system:org.telegram.desktop", options = { remote = "flathub" } },
  { name = "system:dev.vencord.Vesktop", options = { remote = "flathub" } },
  { name = "system:io.anytype.anytype", options = { remote = "flathub" } },
  { name = "system:md.obsidian.Obsidian", options = { remote = "flathub" } },
  { name = "system:com.protonvpn.www", options = { remote = "flathub" } },
  { name = "system:it.mijorus.gearlever", options = { remote = "flathub" } },
  { name = "system:com.github.tchx84.Flatseal", options = { remote = "flathub" } },
  { name = "system:io.github.flattool.Warehouse", options = { remote = "flathub" } },
  { name = "system:io.github.kolunmi.Bazaar", options = { remote = "flathub" } },
  { name = "system:io.github.flattool.Ignition", options = { remote = "flathub" } },
  { name = "system:com.github.marhkb.Pods", options = { remote = "flathub" } },
]
