[arch]
packages = [
  { name = "flatpak", hooks = {
    after_install = ["flatpak", "remote-add", "--if-not-exists", "flathub", "https://dl.flathub.org/repo/flathub.flatpakrepo"],
    after_sync = ["sudo", "flatpak", "mask", "org.freedesktop.Platform.openh264"],
  } },
]

[flatpak]
packages = [
  "org.telegram.desktop",
  "dev.vencord.Vesktop",
  "io.anytype.anytype",
  "md.obsidian.Obsidian",
  "com.protonvpn.www",
  "it.mijorus.gearlever",
  "com.github.tchx84.Flatseal",
  "io.github.flattool.Warehouse",
  "io.github.kolunmi.Bazaar",
  "io.github.flattool.Ignition",
  "com.github.marhkb.Pods",
]
