tap 'vapenyk/homebrew-tap'
tap 'ublue-os/homebrew-tap'

# brew 'bat'
# brew 'eza'
# brew 'fd'
brew 'micro'
brew 'shellcheck'
brew 'ripgrep'
# brew 'zoxide'
brew 'lazygit'
brew 'lazydocker'
brew 'starship'
# brew 'rbw'
brew 'fzf'
brew 'libyaml'
# brew 'gum'

cask 'bitwarden-desktop-linux' # vapenyk
cask 'brave-browser-linux' # vapenyk
cask 'jetbrains-toolbox-linux' # ublue-os
cask 'antigravity-linux' # ublue-os

# Ohhh looovely font
cask 'font-maple-mono-nf'

flatpak 'app.zen_browser.zen'
flatpak 'org.telegram.desktop'
flatpak 'dev.vencord.Vesktop'
flatpak 'com.protonvpn.www'

flatpak 'it.mijorus.gearlever'
flatpak 'com.github.tchx84.Flatseal'
flatpak 'io.github.flattool.Warehouse'
flatpak 'io.github.kolunmi.Bazaar'
flatpak 'io.github.flattool.Ignition'
