# ~/.config/pkg/packages/base.toml

[group]
display = "Base"
description = "CLI tools, shell utilities, fonts"
priority = 10

[paru]
packages = [
  # cli & core
  "base-devel",
  "git",
  "stow",
  "fastfetch",
  "btop",
  "bat",
  "shellcheck",
  "starship",
  "rbw",
  "libyaml",
  "zellij",
  "lazygit",
  "lazydocker",
  "tree-sitter-cli",
  "neovim",
  "micro",
  "lua",
  "luarocks",
  "fzf",
  "ripgrep",
  "fd",
  "mise",
  "nano",
  "nano-syntax-highlighting",
  "openssh",
  "rsync",
  "fsarchiver",
  "wget",
  "curl",

  # wayland core
  "wl-clipboard",

  # AUR
  "maplemono-nf-unhinted",
]

[uv]
packages = [
  "terminaltexteffects",
]
