# ~/.config/pkg/packages/kde.toml

[group]
display = "KDE"
description = "KDE Plasma extras"
priority = 50

[paru]
packages = [
  "klassy",
  "qt6-tools",
  "kde-material-you-colors",
  "plasma6-applets-appgrid",
]
